apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: match-backend
  template:
    metadata:
      labels:
        app: match-backend
    spec:
      containers:
        - name: match-backend
          image: 113701560990.dkr.ecr.ap-northeast-2.amazonaws.com/match-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: AURORA_ENDPOINT
              value: "datingapp-cluster-instance-1.c3wsqyy20d57.ap-northeast-2.rds.amazonaws.com"
            - name: REDIS_ENDPOINT
              value: "match-redis.y1lwij.0001.apn2.cache.amazonaws.com"
            - name: DB_USER
              value: "admin"                      
            - name: DB_PASSWORD
              value: "supersecure123"  # ← DB 비밀번호 (보통 Secret Manager 쓰지만 지금은 하드코딩 가능)
            - name: DB_NAME
              value: "datingapp"                     
            - name: SNS_TOPIC_ARN
              value: "arn:aws:sns:ap-northeast-2:113701560990:match-success-topic"
            - name: AWS_REGION
              value: "ap-northeast-2"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi