apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-app
  labels:
    app: match-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-app
  template:
    metadata:
      labels:
        app: match-app
    spec:
      containers:
      - name: match-app
        image: 113701560990.dkr.ecr.ap-northeast-2.amazonaws.com/match-app:latest
        ports:
        - containerPort: 80        # ✅ 여기 수정
        imagePullPolicy: Always
