apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-api
  labels:
    app: matching-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-api
  template:
    metadata:
      labels:
        app: matching-api
    spec:
      containers:
      - name: matching-api
        image: 113701560990.dkr.ecr.ap-northeast-2.amazonaws.com/matching-api:latest
        ports:
        - containerPort: 3000
