apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matchmind-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jeong-JK/IAM4U.git
    targetRevision: main
    path: frontend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
