name: Deploy to EKS

on:
  push:
    paths:
      - 'terraform/match-backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Image
      run: |
        cd terraform/match-backend
        docker build -t match-backend .
        docker tag match-backend:latest 113701560990.dkr.ecr.ap-northeast-2.amazonaws.com/match-backend:latest
        docker push 113701560990.dkr.ecr.ap-northeast-2.amazonaws.com/match-backend:latest

    - name: Deploy to EKS
      run: |
        aws eks update-kubeconfig --region ap-northeast-2 --name match-cluster
        kubectl rollout restart deployment match-backend

